### ISSUE TITLE
We need to make sure the body is sent as UTF8 using [System.Text.Encoding]::UTF8.GetBytes($body)

### ISSUE THREAD

**Issue by arnoutvandervorst** [Tools4everBV/HelloID-Conn-Prov-Target-Google-Workspace#3]
https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-GSuite/blob/3674535d3622bf4cd636dd4d3f6686f17d55b9f4/create.ps1#L155

Also: -ContentType "application/json; charset=utf-8"

**Comment by msheldont4e** [comment]
Solved in v3
